export const GET_PAGES = {
    READY: 'GET_PAGES_READY',
    FAILURE: 'GET_PAGES_FAILURE',
    SUCCESS: 'GET_PAGES_SUCCESS'
}
export const GET_COMMUNITY = {
    READY: 'GET_COMMUNITY_READY',
    FAILURE: 'GET_COMMUNITY_FAILURE',
    SUCCESS: 'GET_COMMUNITY_SUCCESS'
}
export const GET_BOARD = {
    READY: 'GET_BOARD_READY',
    FAILURE: 'GET_BOARD_FAILURE',
    SUCCESS: 'GET_BOARD_SUCCESS'
}
export const GET_CONTENT = {
    READY: 'GET_CONTENTS_READY',
    FAILURE: 'GET_CONTENTS_FAILURE',
    SUCCESS: 'GET_CONTENTS_SUCCESS'
}



export const POST_CRAETE_PAGE = {
    READY: 'POST_CRAETE_PAGE_READY',
    FAILURE: 'POST_CRAETE_PAGE_FAILURE',
    SUCCESS: 'POST_CRAETE_PAGE_SUCCESS'
}